POST https://api.z.ai/api/paas/v4/chat/completions HTTP/1.1
Content-Type: application/json
Authorization: 43e13e521e434ab691b0487abab934bf.b8QtdHyIimzVtlTj

{
    "model": "glm-4.5-flash",
    "messages": [
    {
    "role": "user",
    "content": "As a marketing expert, please create an attractive slogan for my product."
    },
    {
    "role": "assistant",
    "content": "Sure, to craft a compelling slogan, please tell me more about your product."
    },
    {
    "role": "user",
    "content": "Z.AI Open Platform"
    }
    ],
    "thinking": {
    "type": "enabled"
    },
    "max_tokens": 1024,
    "temperature": 1.0
}

###
GET http://api.openweathermap.org/data/2.5/weather?q=Moscow&appid=b52d0750fb10146367ad7a8a141703db HTTP/1.1